# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90bb79e2e9854cc86f3e9b76a47a0743fdf1f462aab7ec315f8a739e4437f20a14e0a1312dc5d8a88a0ae1637e4ff33c3f58f44e8282eca6a0ec9582aa1d6fae

test:
  secret_key_base: a62cc5e3fad981784abd403c4f4bb94b5b4c1a3353f3f3216b02f42faacd42517857240e3789a8a203ed46248b996150c4f77c6bd8fee9dfac0382beda850dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
